name: Increment Counter

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  increment-counter:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Step 3: Run Increment Counter Script
      - name: Increment Counter
        run: |
          node -e "
          const fs = require('fs');
          const filePath = './last_watched.json';
          const data = fs.existsSync(filePath) ? JSON.parse(fs.readFileSync(filePath, 'utf8')) : { count: 0 };
          data.count = (data.count || 0) + 1;
          fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
          console.log('Updated count to:', data.count);
          "

      # Step 4: Commit and push changes if there are any
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add last_watched.json
          git commit -m "Increment counter"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
