name: Pokémon Discord Notification

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  send-pokemon-notification:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Navigate to the correct directory
    - name: Navigate to project directory
      working-directory: Discord-Webhook-Sender/pokemon # Change this to your package.json directory

    # Step 3: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Step 4: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 5: Run the script
    - name: Run Pokémon Notification Script
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: node pokemon-discord.js
