name: Pokémon Discord Notification

on:
  schedule:
    - cron: '0 9 * * *' # Runs daily at 9 AM UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  send-pokemon-notification:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Step 3: Install axios (no package.json)
    - name: Install Dependencies
      run: npm install
      working-directory: ./pokemon
    # Step 4: Run the script
    - name: Run Pokémon Notification Script
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: node pokemon/pokemon.js
